<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRmeX9tP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRmeX9tP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRmeX9tP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRmeX9tP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRmeX9tP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RmeX9tP',
    'container.build_id' => '440eb412',
    'container.build_time' => 1558961520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRmeX9tP');
