<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSuk2dxm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSuk2dxm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSuk2dxm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSuk2dxm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSuk2dxm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Suk2dxm',
    'container.build_id' => 'e891b7c0',
    'container.build_time' => 1558446145,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSuk2dxm');
