<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAgZt15S\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAgZt15S/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAgZt15S.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAgZt15S\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAgZt15S\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AgZt15S',
    'container.build_id' => 'bc19622f',
    'container.build_time' => 1557749978,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAgZt15S');
